#include <iostream>
#include <string>
#include <fstream>
#include <cwchar>
#include <ctime>
#include <wchar.h>
#include <tchar.h>
#include <locale>
#include <stack>
#include <list>
#include <iomanip>
